export const FETCH_PLAYER_ID_REQUEST = 'FETCH_PLAYER_ID_REQUEST'
export const FETCH_PLAYER_ID_SUCCESS = 'FETCH_PLAYER_ID_SUCCESS'

export const FETCH_PLAYER_STATS_REQUEST = 'FETCH_PLAYER_STATS_REQUEST'
export const FETCH_PLAYER_STATS_SUCCESS = 'FETCH_PLAYER_STATS_SUCCESS'

export const FETCH_ALL_PLAYER_REQUEST = 'FETCH_ALL_PLAYER__REQUEST'
export const FETCH_ALL_PLAYER_SUCCESS = 'FETCH_ALL_PLAYER_SUCCESS'

export const HIDE_RESULTS = 'HIDE_RESULTS'
export const SHOW_INPUT_ERROR = 'SHOW_INPUT_ERROR'
export const REMOVE_PLAYER = 'REMOVE_PLAYER'

export const UPDATE_STATS_BAR_PLOT = 'UPDATE_STATS_BAR_PLOT'
export const UPDATE_STATS_SCATTER_PLOT_X = 'UPDATE_STATS_SCATTER_PLOT_X'
export const UPDATE_STATS_SCATTER_PLOT_Y = 'UPDATE_STATS_SCATTER_PLOT_Y'

export const SHOW_LOADER = 'SHOW_LOADER'
